### Logback Configuration
logging:
  level:
    root: INFO
    me.weteam: DEBUG
    org.springframework.web: INFO

## Swagger configuration
swagger:
  enabled: true
  title: ${info.build.name}
  description: ${info.build.description}
  version: ${info.build.version}
  base-package: me.weteam.user
  base-path: /api/**
